### Get /
GET http://localhost:2104

### POST auth/register
POST http://localhost:2104/auth/register
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "123123123"
}

### POST auth/login
POST http://localhost:2104/auth/login
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "123123123"
}

### Get /todos
GET http://localhost:2104/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM5ODcyNDk2LCJleHAiOjE3Mzk5NTg4OTZ9.IILKr3JbgxYTYlZZJgXYowSmzuuQA1u5OlHlnfBHfkY

### POST /todos
POSt http://localhost:2104/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM5ODcyNDk2LCJleHAiOjE3Mzk5NTg4OTZ9.IILKr3JbgxYTYlZZJgXYowSmzuuQA1u5OlHlnfBHfkY
Content-Type: application/json

{
    "task": "Finish coding project"
}

### PUT /todos
PUT http://localhost:2104/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM5ODcyNDk2LCJleHAiOjE3Mzk5NTg4OTZ9.IILKr3JbgxYTYlZZJgXYowSmzuuQA1u5OlHlnfBHfkY
Content-Type: application/json

{
    "task": "Finished Coding",
    "completed": 1
}

### PUT /todos
DELETE http://localhost:2104/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM5ODcyNDk2LCJleHAiOjE3Mzk5NTg4OTZ9.IILKr3JbgxYTYlZZJgXYowSmzuuQA1u5OlHlnfBHfkY
Content-Type: application/json
