### POST /auth/register
POST http://localhost:2104/auth/register
Content-Type: multipart/form-data

{
    "username": "admin",
    "email": "admin@admin.com",
    "password": "123456789",
    "image": ""
}

### POST /auth/login
POST http://localhost:2104/auth/login
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzQwMTI3MDcwLCJleHAiOjE3NDAyMTM0NzB9.K5hVYPmZCQIRnJSNAVkoKqehDwqnXElWfTbGcu25iy4

{
    "username": "admin",
    "email": "admin@admin.com",
    "password": "123456789"
}

### GET /blogs/all
GET http://localhost:2104/home/all?limit=3


### GET /blogs
### for this user only
GET http://localhost:2104/blogs
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNjczMjk3LCJleHAiOjE3NDA3NTk2OTd9.dS40NbeiN1UnKl7cgqF12BNFiyUyzc8EYG0weI03wOI

### GET /blogs/:id
GET http://localhost:2104/blogs/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwMzgxMDk3LCJleHAiOjE3NDA0Njc0OTd9.CPxFIYxf-3P3a5yED2drG5lSLO0SRI1KPkQJgmn2AB8

### POST /blogs
POST http://localhost:2104/blogs
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwMzgxMDk3LCJleHAiOjE3NDA0Njc0OTd9.CPxFIYxf-3P3a5yED2drG5lSLO0SRI1KPkQJgmn2AB8

{
    "title": "Testing new user",
    "description": "New user test",
    "content": "Testing if the limit attribute works in recent blog function",
    "tags": ["Tech","Games","Siege"],
    "image": "https://images.unsplash.com/photo-1485988412941-77a35537dae4?q=80&w=1792&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

### PUT /blogs/:id
PUT http://localhost:2104/blogs/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNjczMjk3LCJleHAiOjE3NDA3NTk2OTd9.dS40NbeiN1UnKl7cgqF12BNFiyUyzc8EYG0weI03wOI

{
    "title": "Edited the title for this blog 2",
    "description": "Edited description"

}

### DELETE /blogs/:id
DELETE http://localhost:2104/blogs/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzQwMDI3NjIzLCJleHAiOjE3NDAxMTQwMjN9.CDkeAMvpnB6LBnRFqZqXnSOsxJvCbXvxXtUonYjxPR8

### GET /users/id
GET http://localhost:2104/auth/users/2
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQwNjczNzMzLCJleHAiOjE3NDA3NjAxMzN9.-wgoag3COiGisEb_buGINl-1lu9QI7pMUWrvOiUx52w
